{% set version = "2010.07.06" %}

package:
  name: child
  version: {{ version }}

source:
  url: https://github.com/childmodel/child/archive/{{ version }}.tar.gz
  sha256: 7b6e4338b5514e38f7fd6cdcdd3b45c5a9a90074bc8f3d2f5bc310d3a3d16237
  patches:
    - remove_predicate.patch

build:
  skip: true  # [win and vc<14]
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cmake
    - pkg-config  # [win]
    - bmi-cxx

test:
  commands:
    - child --help
    - child --version

about:
  home: http://csdms.colorado.edu/wiki/Model:CHILD
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The CHILD Landscape Evolution Model
  description: |
    CHILD computes the time evolution of a topographic surface z(x,y,t)
    by fluvial and hillslope erosion and sediment transport.
  doc_url: http://csdms.colorado.edu/wiki/Model:CHILD
  dev_url: https://github.com/childmodel/child

extra:
  recipe-maintainers:
    - mcflugen
