{% set version = "21.03.12" %}

package:
  name: child
  version: {{ version }}

source:
  url: https://github.com/childmodel/child/archive/v{{ version }}.tar.gz
  sha256: 1773d76b4e9ee8a54c962700b6fc988f67f26025a0e8b31f4d90646eaaccd19c
  patches:
    - remove_predicate.patch

build:
  skip: True  # [win and vc<14]
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
  host:
    - cmake
    - pkg-config  # [win]
    - bmi-cxx

test:
  commands:
    - child --help
    - child --version

about:
  home: http://csdms.colorado.edu/wiki/Model:CHILD
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The CHILD Landscape Evolution Model
  description: |
    CHILD computes the time evolution of a topographic surface z(x,y,t)
    by fluvial and hillslope erosion and sediment transport.
  doc_url: http://csdms.colorado.edu/wiki/Model:CHILD
  dev_url: https://github.com/childmodel/child

extra:
  recipe-maintainers:
    - mcflugen
