{% set version = "18.11.12" %}

package:
  name: child
  version: {{ version }}

source:
  url: https://github.com/childmodel/child/archive/v{{ version }}.tar.gz
  sha256: 8542a3e7ce4df5e5f41cf46c911294b202d9db06ce45546b04bee3b4eb34accc

build:
  skip: True  # [win]
  number: 1001

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - child --help
    - child --version

about:
  home: http://csdms.colorado.edu/wiki/Model:CHILD
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The CHILD Landscape Evolution Model
  description: |
    CHILD computes the time evolution of a topographic surface z(x,y,t)
    by fluvial and hillslope erosion and sediment transport.
  doc_url: http://csdms.colorado.edu/wiki/Model:CHILD
  dev_url: https://github.com/childmodel/child

extra:
  recipe-maintainers:
    - mcflugen
