travis:
  secure:
    BINSTAR_TOKEN: W+YyH0Nm1g4zTjKotDZouTfu5zdw/18JVbw454c33ZuLthp/xFOoHLFLeL1tWZCzc2GOmtoRtvP9onPvtKJ0ZAr3bRhh7+IgHfZUPHK5ckKH3iBcSCXSUX/B3IrN9etob4znlscRG6nfDWuewWauon1lF7HU0IIuQ45KQiQShAF8DalME2HO9OfFxtmIX3qCDAZZb3GlZs3zoNLUt+dA56srG9u3724wT3nrEnop7ynf6ec9CYbuuSZU3TWKSYc8wPFjXwMkQDKmvhFHG0f59dTaGuhO3P3v6x9H7SV2mosrC3cxm7L/MegIrOmsaBU42CuG/tOlraBvQbKvtsAlYRAh4KJRUocr51Z+TGLtyiJHFJGsVOMrARI3Acubj5S3GD1QYOD41FVYiQY6NLNj+/MMZ+wzPi7cEekoDkSgZ6f2Hu9eEttHO2Yu0woHTYzbx0AGzPXBiC3fMhySzfuYDvhVEeUj8X6QbUaP1xN9gm02ddztRCeXbISUa0k35KkKcesNzGdDQ+29xqDbarHs1WN2IUTxfLr4ZoljNbREsMe4nw0AjMuMtPnlytLbt9WkJYFhD/bSVRT2vpdt0hyHxao2lxt2fY4LhWb05HWmxdKufSTnhsG31aUWt+4m94ZScFW76nmvThFpXiFUmf71IoToZpnFyeGuOIB4cup9pio=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
